version: '3.4'

services:
  dockerapp:
    image: ${DOCKER_REGISTRY}dockerapp
    build:
      context: .
      dockerfile: DockerApp/Dockerfile

  dockermvc:
      image: ${DOCKER_REGISTRY}dockermvc
      build:
        context: .
        dockerfile: DockerMVC\Dockerfile